[package]
name = "stark_precompile"
version = "0.1.0"
edition = "2021"

[lib]
name = "stark_verifier"
crate-type = ["staticlib"]

[dependencies]
bincode = "1.3"
hex = "0.4"
risc0-zkvm = { version = "0.21", features = ["prove"] }
hello-world-methods = { path = "methods" }